apiVersion: v1
kind: Service
metadata:
  name: book-price
  labels:
    app: book-price
spec:
  ports:
  - port: 50050
    name: http
    protocol: TCP
    targetPort: 50050

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: book-price-svc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: book-price-svc
        language: go
    spec:
      containers:
      - name: book-price-svc
        image: xovox/sample-book-price:0.1
        ports:
        - containerPort: 50050
        env:
          - name: DATABASE_URL
            value: "root:abc123@tcp(db:3306)/PRICEINFO"
          - name: PORT
            value: ":50050"